### ISSUE TITLE
ASTC support

### ISSUE THREAD

**Issue by halx99** [c4games/engine-v5#37]

**Comment by weiwest** [comment]
the official repository is here
https://github.com/ARM-software/astc-encoder

the support of ASTC is implemented by Hardware decoding
software decoding is on the way

Support profile:
    2D image
    LDR(Low Dynamic Range)
    SRGB Color Space

Support block size 
    4x4 8 bits/pixel
    8x8 2 bits/pixel
why not other block size
Because Texture2D PixelFormatInfo bpp is int, other block size is not available.

Alpha
    ASTC Support 1-4 channel,
    you can compress png file, to get RGBA Texture.
    or compress jpg file, to get RGB Texture.

Flip
    ASTC Texture display flip through OpenGL
    stcenc uses the DirectX coordinate system (where 0,0 is at the top left of the image), 
    This is different to other compressors, like etcpack, 
    recommend using a tool like ImageMagick to flip source images.

Command-line tool example
    .\astcenc.exe -cs xxx.png xxx.astc  8x8  -medium
    .\astcenc.exe -cs xxx.jpg xxx.astc  4x4  -medium

recommend the latest version 1.7

**Comment by halx99** [comment]
see also: https://github.com/c4games/engine-v5/pull/50

**Comment by halx99** [comment]
Since major ASTC support implementation is finlished, close this issue
